services:
  whisper-asr-webservice:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASR_MODEL=${ASR_MODEL}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./app:/app/app
      - cache-whisper:/root/.cache

volumes:
  cache-whisper:
